nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.0.cjs

npmScopes:
  fjanicki:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://github.com/api/v4/packages/npm/"
